BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS history_classes (
	id	INTEGER NOT NULL,
	historyId	INTEGER NOT NULL,
	classId	INTEGER NOT NULL,
	FOREIGN KEY(classId) REFERENCES classes(id),
	PRIMARY KEY(id),
	FOREIGN KEY(historyId) REFERENCES history(id)
);
CREATE TABLE IF NOT EXISTS history (
	id	INTEGER NOT NULL,
	imagePath	TEXT NOT NULL,
	scanDate	DATE NOT NULL,
	isLastScan	BOOLEAN NOT NULL,
	userId	INTEGER NOT NULL,
	PRIMARY KEY(id),
	CHECK(isLastScan IN (0,1)),
	FOREIGN KEY(userId) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS classes (
	id	INTEGER NOT NULL,
	name	VARCHAR(100) NOT NULL,
	classifierId	INTEGER NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(classifierId) REFERENCES classifiers(id)
);
CREATE TABLE IF NOT EXISTS users (
	id	INTEGER NOT NULL,
	username	VARCHAR(100) NOT NULL,
	email	VARCHAR(200) NOT NULL,
	password	VARCHAR(1000) NOT NULL,
	isAdmin	BOOLEAN NOT NULL,
	PRIMARY KEY(id),
	CHECK(isAdmin IN (0,1))
);
CREATE TABLE IF NOT EXISTS classifiers (
	id	INTEGER NOT NULL,
	name	VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY(id)
);
COMMIT;
